name: Flutter CI

on:
  push:
    branches: [main, develop, "feat/**", "fix/**", "chore/**"]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze code
        run: flutter analyze
      - name: Run tests
        run: flutter test
